<?php
    $default_attribs = array(
        'id'                   => array(),
        'class'                => array(),
        'title'                => array(),
        'style'                => array(),
        'href'                 => array(),
        'target'               => [
            '_blank',
        ],
        'colspan'              => array(),
        'rowspan'              => array(),
        'aria-checked'         => array(),
        'aria-controls'        => array(),
        'aria-disabled'        => array(),
        'aria-expanded'        => array(),
        'aria-hidden'          => array(),
        'aria-label'           => array(),
        'aria-selected'        => array(),
        'data-open-first-item' => array(),
        'data-target'          => array(),
    );

    $allowed_html = [
        'h2'     => $default_attribs,
        'h3'     => $default_attribs,
        'div'    => $default_attribs,
        'span'   => $default_attribs,
        'p'      => $default_attribs,
        'a'      => $default_attribs,
        'button' => $default_attribs,
        'br'     => $default_attribs,
        'strong' => $default_attribs,
        'b'      => $default_attribs,
        'i'      => $default_attribs,
        'em'     => $default_attribs,
        'ul'     => $default_attribs,
        'ol'     => $default_attribs,
        'li'     => $default_attribs,
        'table'  => $default_attribs,
        'thead'  => $default_attribs,
        'tbody'  => $default_attribs,
        'th'     => $default_attribs,
        'tr'     => $default_attribs,
        'td'     => $default_attribs,
    ];
